export const students = [
  { id: 1, name: "Sam Smith", year: 3, average: 4.1 },
  { id: 2, name: "Olivia Jones", year: 1, average: 3.8 },
  { id: 3, name: "Noah Miller", year: 2, average: 2.8 },
  { id: 4, name: "Mia Garcia", year: 1, average: 3.5 },
  { id: 5, name: "Ethan Lee", year: 2, average: 2.9 },
  { id: 6, name: "Sophia Hernandez", year: 3, average: 4.0 },
  { id: 7, name: "Liam Johnson", year: 1, average: 3.0 },
  { id: 8, name: "Ava Davis", year: 2, average: 3.2 },
  { id: 9, name: "William Brown", year: 2, average: 4.2 },
  { id: 10, name: "Isabella Wilson", year: 1, average: 3.7 },
  { id: 11, name: "James Taylor", year: 2, average: 3.1 },
  { id: 12, name: "Charlotte Moore", year: 2, average: 4.0 },
  { id: 13, name: "Benjamin Thomas", year: 3, average: 2.7 },
  { id: 14, name: "Emily Garcia", year: 1, average: 4.8 },
  { id: 15, name: "Michael Young", year: 2, average: 3.4 },
  { id: 16, name: "Ashley Hernandez", year: 2, average: 3.3 },
  { id: 17, name: "Daniel Lopez", year: 1, average: 3.9 },
  { id: 18, name: "Madison Allen", year: 2, average: 3.3 },
  { id: 19, name: "Christopher Clark", year: 3, average: 4.1 },
  { id: 20, name: "Abigail King", year: 2, average: 3.8 },
];
